# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    tags: ["*"]

env:
  IMAGE_NAME: ducminhgd/go-gitops

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install buildx
      run: docker buildx create --name builder-x --use --driver docker-container
    - name: Build the Docker image
      run: docker buildx build
          --output=type=image,name=$IMAGE_NAME,oci-mediatypes=true,push=true
          --tag=$IMAGE_NAME:$GITHUB_REF_NAME .
